version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-water-gas-management
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
  
  db:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80

volumes:
  pgdata:

networks:
  default:
    name: local-network
    external: true